version: 2.1
orbs:
  ruby: circleci/ruby@1.7.1
  node: circleci/node@5.0.2

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.6-node
    working_directory: ~/sampleapp-yut/src
    steps:
      - checkout:
          path: ~/sampleapp-yut
      - ruby/install-deps


  test:
    docker:
      - image: cimg/ruby:2.7-node
      - image: cimg/postgres:14.2
        environment:
          POSTGRES_PASSWORD: password
          POSTGRES_DATABASE: myapp_test
          POSTGRES_USER: postgres
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      MYAPP_DATABASE_HOST: "127.0.0.1"
      RAILS_ENV: test
    working_directory: ~/sampleapp-yut/src
    steps:
      - checkout:
          path: ~/sampleapp-yut
      - ruby/install-deps
      - run:
          name: yarn Install
          command: yarn install
      - run: bundle exec bin/webpack
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client
      - run: whoami
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load
      - run:
          name: Database setup
          command: bundle exec rails db:migrate
      - run:
          name: test
          command: bundle exec rake test


workflows:
  version: 2
  build_test:
    jobs:
      - build
      - test:
          requires:
            - build
